services:
  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: cardtrades
      POSTGRES_PASSWORD: cardtrades
      POSTGRES_DB: cardtrades
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U cardtrades -d cardtrades']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata_dev:
